# Supervised Learning Model Evaluation Lab

Complete the exercises below to solidify your knowledge and understanding of supervised learning model evaluation.

In [1]:
import pandas as pd

## Regression Model Evaluation

In [2]:
from sklearn.datasets import load_boston

data = load_boston()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=['MEDV'])

data = pd.concat([X, y], axis=1)

In [3]:
data.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

## 1. Split this data set into training (80%) and testing (20%) sets.

The `MEDV` field represents the median value of owner-occupied homes (in $1000's) and is the target variable that we will want to predict.

In [4]:
from sklearn.model_selection import train_test_split

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

## 2. Train a `LinearRegression` model on this data set and generate predictions on both the training and the testing set.

In [6]:
from sklearn.linear_model import LinearRegression

In [7]:
linReg = LinearRegression()

In [8]:
linReg.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [9]:
y_pred_test = linReg.predict(X_test) 

In [14]:
y_pred_train = linReg.predict(X_train) 

## 3. Calculate and print R-squared for both the training and the testing set.

In [12]:
from sklearn.metrics import r2_score

score_test = r2_score(y_test, y_pred_test)
score_test

0.6513951312371714

In [15]:
score_train = r2_score(y_train, y_pred_train)
score_train

0.7604964395812646

## 4. Calculate and print mean squared error for both the training and the testing set.

In [16]:
from sklearn.metrics import mean_squared_error
mse_test = mean_squared_error(y_test, y_pred_test)
mse_test

33.61225091924754

In [17]:
mse_train = mean_squared_error(y_train, y_pred_train)
mse_train

19.49156667010001

## 5. Calculate and print mean absolute error for both the training and the testing set.

In [18]:
from sklearn.metrics import mean_absolute_error
mae_test = mean_absolute_error(y_test, y_pred_test)
mae_test

3.942668962877747

In [19]:
mae_train = mean_absolute_error(y_train, y_pred_train)
mae_train

3.015305376537211

In [21]:
import numpy as np
rmse_test = np.sqrt(mean_absolute_error(y_test, y_pred_test))
rmse_test

1.9856155123481856

In [22]:
rmse_train = np.sqrt(mean_absolute_error(y_train, y_pred_train))
rmse_train

1.7364634682414746

## Classification Model Evaluation

In [23]:
from sklearn.datasets import load_iris

data = load_iris()

X = pd.DataFrame(data["data"], columns=data["feature_names"])
y = pd.DataFrame(data["target"], columns=["class"])

data = pd.concat([X, y], axis=1)

In [36]:
data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   class  
0      0  
1      0  
2      0  
3      0  
4      0

In [44]:
data['class'].unique()

array([0, 1, 2], dtype=int64)

## 6. Split this data set into training (80%) and testing (20%) sets.

The `class` field represents the type of flower and is the target variable that we will want to predict.

In [24]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

## 7. Train a `LogisticRegression` model on this data set and generate predictions on both the training and the testing set.

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
logmodel = LogisticRegression()
logmodel.fit(X_train,y_train)

C:\Users\ferna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\Users\ferna\Anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\ferna\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [27]:
predictions_test = logmodel.predict(X_test)

In [28]:
predictions_train = logmodel.predict(X_train)

## 8. Calculate and print the accuracy score for both the training and the testing set.

In [47]:
from sklearn.metrics import accuracy_score

In [49]:
accuracy_score(y_test,predictions_test)

0.7666666666666667

In [50]:
accuracy_score(y_train,predictions_train)

0.95

## 9. Calculate and print the balanced accuracy score for both the training and the testing set.

In [51]:
from sklearn.metrics import balanced_accuracy_score

In [52]:
balanced_accuracy_score(y_test,predictions_test)

0.8703703703703703

In [53]:
balanced_accuracy_score(y_train,predictions_train)

0.9375

## 10. Calculate and print the precision score for both the training and the testing set.

In [54]:
from sklearn.metrics import precision_score

In [56]:
precision_score(y_test,predictions_test, average='weighted')

0.8833333333333333

In [57]:
precision_score(y_train,predictions_train, average='weighted')

0.9561224489795919

## 11. Calculate and print the recall score for both the training and the testing set.

In [58]:
from sklearn.metrics import recall_score

In [60]:
recall_score(y_test,predictions_test, average='weighted')

0.7666666666666667

In [61]:
recall_score(y_train,predictions_train, average='weighted')

0.95

## 12. Calculate and print the F1 score for both the training and the testing set.

In [63]:
from sklearn.metrics import f1_score

In [65]:
f1_score(y_test,predictions_test, average='weighted')

0.7773946360153255

In [66]:
f1_score(y_train,predictions_train, average='weighted')

0.949044227886057

## 13. Generate confusion matrices for both the training and the testing set.

In [38]:
from sklearn.metrics import multilabel_confusion_matrix

In [39]:
cm_test=multilabel_confusion_matrix(y_test,predictions_test)
print(cm_test)

[[[25  0]
  [ 0  5]]

 [[12  0]
  [ 7 11]]

 [[16  7]
  [ 0  7]]]


In [40]:
cm_train=multilabel_confusion_matrix(y_train,predictions_train)
print(cm_train)

[[[75  0]
  [ 0 45]]

 [[88  0]
  [ 6 26]]

 [[71  6]
  [ 0 43]]]


## Bonus: For each of the data sets in this lab, try training with some of the other models you have learned about, recalculate the evaluation metrics, and compare to determine which models perform best on each data set.