
<p>Agora que começa a brincadeira, o primeiro passo é importar o numpy, usando o famoso:</p>


In [1]:

import numpy as np




<h1 id="CRIANDO-ARRAYS">CRIANDO ARRAYS<a class="anchor-link" href="#CRIANDO-ARRAYS">¶</a></h1>



<p>Existem várias formas de criar arrays, pode ser através do método np.array(), usando uma lista ou tupla do python:</p>


In [8]:

arr = np.array([-2, 4.3, 7, 9])

my_tuple = (8, -5, 0, 3.2)
arr2 = np.array(my_tuple)

print('arr = ', arr)
print('arr2 = ', arr2)



arr =  [-2.   4.3  7.   9. ]
arr2 =  [ 8.  -5.   0.   3.2]



<p>Usando o método arange (similar ao range do python)</p>


In [9]:

arr = np.arange(10)
print(arr, '\n')

# Lembrando que arrays podem ter mais de uma dimensão
# cria uma array começando em 2 e até 32 (sem incluí-lo),  pulando cada dois números

arr2 = np.arange(1, 32, 2).reshape(4, 4) # reshape muda o formato da array - nesse caso de (16) para (4x4)
print(arr2)



[0 1 2 3 4 5 6 7 8 9] 

[[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]



<p>Usando os métodos 'zeros()' e 'ones()' para criar arrays de 0 e 1, respectivamente:</p>


In [10]:

arr = np.zeros(8) # array contendo 8 'zeros'
print (arr)

arr2 = np.ones((4,3)) # array contendo 12 'uns', no formato 4 x 3
print(arr2)



[ 0.  0.  0.  0.  0.  0.  0.  0.]
[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [11]:

# Método linspace()

arr = np.linspace(1, 100, 10) # de 1 a 100, contendo 10 valores
print(arr, '\n')


# Array vazia com o método empty()

arr2 = np.empty((6,4)) # normalmente a saída é lixo de memória ou zeros
print(arr2, '\n')


# Np.Eye
#matriz identidade:

arr3 = np.eye(4) # eye cria uma array de duas dimensões com 1 na da diagnoal e 0 nos outros elementos
print(arr3)



[   1.   12.   23.   34.   45.   56.   67.   78.   89.  100.] 

[[  6.94175906e-310   2.63421731e-316   7.18150915e-299   7.18150915e-299]
 [  7.18150915e-299   7.18150915e-299   7.18150915e-299   7.18150915e-299]
 [  7.18150915e-299   7.18150915e-299   7.18150915e-299   7.18150915e-299]
 [  7.18150915e-299   7.18150915e-299   7.18150915e-299   7.18150915e-299]
 [  3.72885274e-265   7.17217651e-299   7.17217651e-299   7.17217651e-299]
 [  7.17334309e-299   7.16867678e-299   7.16867678e-299   2.48672696e-316]] 

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]



<h2 id="ATRIBUTOS-DAS-ARRAYS">ATRIBUTOS DAS ARRAYS<a class="anchor-link" href="#ATRIBUTOS-DAS-ARRAYS">¶</a></h2>



<p>Existem vários atributos, mas o três principais são .shape , .size e .dtype</p>


In [12]:

arr = np.linspace(.5, 50, 10)

print('.shape: ', arr.shape)    # imprime o formato da array
print('.size: ', arr.size)      # imprime o tamanho da array
print('.dtype: ', arr.dtype)    # imprime o tipo de dado dos elementos



.shape:  (10,)
.size:  10
.dtype:  float64



<p>Outros atributos:</p>


In [13]:

print('.ndim: ', arr.ndim)          # número de dimensões
print('.itemsize: ', arr.itemsize)      # tamanho de cada elemento em bytes



.ndim:  1
.itemsize:  8



<h2 id="OPERAÇÕES-BÁSICAS">OPERAÇÕES BÁSICAS<a class="anchor-link" href="#OPERAÇÕES-BÁSICAS">¶</a></h2>



<p>É bem fácil realizar operações matemáticas com arrays</p>


In [14]:

# vamos criar as arrays A e B para fazer operações com elas

A = np.arange(10)
B = np.arange(10,38,3)
C = np.arange(9).reshape(3,3)
D = np.arange(10,37,3).reshape(3,3)

print (' A: ', A, '\n', 'B: ', B,'\n\n','C:',C,'\n\n','D:',D)



 A:  [0 1 2 3 4 5 6 7 8 9] 
 B:  [10 13 16 19 22 25 28 31 34 37] 

 C: [[0 1 2]
 [3 4 5]
 [6 7 8]] 

 D: [[10 13 16]
 [19 22 25]
 [28 31 34]]


In [15]:

somar = A + B
subtrair = A - B
dividir = A / B
multiplicar = A * B

print('somar: ', somar )
print('subtrair: ', subtrair )
print('dividir: ', dividir )
print('multiplicar: ', multiplicar)



somar:  [10 14 18 22 26 30 34 38 42 46]
subtrair:  [-10 -12 -14 -16 -18 -20 -22 -24 -26 -28]
dividir:  [ 0.          0.07692308  0.125       0.15789474  0.18181818  0.2
  0.21428571  0.22580645  0.23529412  0.24324324]
multiplicar:  [  0  13  32  57  88 125 168 217 272 333]


In [16]:

a = list(range(10))
b = list(range(10,38,3))
soma1 = a + b
print("soma1: ", soma1)
soma2 = [a[i] + b[i] for i in range(len(a))]
print("soma2: ", soma2)



soma1:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37]
soma2:  [10, 14, 18, 22, 26, 30, 34, 38, 42, 46]


In [17]:

somar = C + D
subtrair = C - D
dividir = C / D
multiplicar = C * D

print('somar:\n', somar )
print('\n\n subtrair:\n', subtrair )
print('\n\n dividir:\n', dividir )
print('\n\n multiplicar:\n', multiplicar)



somar:
 [[10 14 18]
 [22 26 30]
 [34 38 42]]


 subtrair:
 [[-10 -12 -14]
 [-16 -18 -20]
 [-22 -24 -26]]


 dividir:
 [[ 0.          0.07692308  0.125     ]
 [ 0.15789474  0.18181818  0.2       ]
 [ 0.21428571  0.22580645  0.23529412]]


 multiplicar:
 [[  0  13  32]
 [ 57  88 125]
 [168 217 272]]


In [18]:

# para realmente fazer uma multiplicação de matrizes, devemos utilizar o comando numpy.dot()

print(C.dot(D))
print("\n",0*10 + 1*19 + 2* 28) #elemento: linha 1 x coluna 1



[[ 75  84  93]
 [246 282 318]
 [417 480 543]]

 75



<h4 id="Perceba-que-se-você-dividir-por-zero,-numpy-não-vai-dar-erro-(o-código-vai-rodar),-porém-vai-emitir-uma-advertência!">Perceba que se você dividir por zero, numpy não vai dar erro (o código vai rodar), porém vai emitir uma advertência!<a class="anchor-link" href="#Perceba-que-se-você-dividir-por-zero,-numpy-não-vai-dar-erro-(o-código-vai-rodar),-porém-vai-emitir-uma-advertência!">¶</a></h4>


In [19]:

B/A     # a array A contém um zero como primeiro elemento



/home/fernanda/.local/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([         inf,  13.        ,   8.        ,   6.33333333,
         5.5       ,   5.        ,   4.66666667,   4.42857143,
         4.25      ,   4.11111111])


<p>BROADCAST = transmissão</p>


In [20]:

''' Você pode fazer operações envolvendo arrays e um único elemento, dessa forma numpy itera a operação 
do elemento único com todos os componentes da array, exemplo: ''' 

A * 100    # retorna um array com a multiplicação de todos elementos da array por 100



array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [21]:

print(" A + 1: ", A + 1)
print(" a + 1: ", a + [1])
# Este comando gerará um erro conceitual, pois estamos tentando concatenar uma lista com um inteiro 
# não soma 1, e sim, concatena
# print(" a + 1: ", a + 1)



 A + 1:  [ 1  2  3  4  5  6  7  8  9 10]
 a + 1:  [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 1]



<h2 id="INDEXAÇÃO-E-FATIAMENTO-(SLICING)">INDEXAÇÃO E FATIAMENTO (SLICING)<a class="anchor-link" href="#INDEXAÇÃO-E-FATIAMENTO-(SLICING)">¶</a></h2>



<p>O acesso de elementos de uma array, funciona de forma similar ao das listas do Python:</p>


In [39]:

# criar uma array com o quadrado dos números de 1 a 10
arr = np.arange(1, 10) **2
arr



array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [40]:

# acessando o primeiro elemento
print('1º elemento: ', arr[0])    # lembrar que índice começa do 0

# acessando o quinto elemento
print ('5º elemento: ', arr[4])   # O quinto elemento é acessado pelo índice 4



1º elemento:  1
5º elemento:  25


In [41]:

# Em um array de duas dimensões (ou mais) existem duas formas de acessar o índice:

arr = arr.reshape((3,3))
print (arr, '\n')

#Para acessar um elemento, pode-se usar essas duas formas de sintaxe:

# Usando colchetes duplos [][]
print ('Acessando o elemento 25: ', arr[1][1])

# Ou minha preferência pessoal - separando índices por vírgula
print ('Acessando o elemento 25: ', arr[1,1])

# acessando o último elemento usando o -1
arr[-1, -1] 



[[ 1  4  9]
 [16 25 36]
 [49 64 81]] 

Acessando o elemento 25:  25
Acessando o elemento 25:  25


81

In [42]:

# Para acessar fatias de elementos, usamos o slice [i:i], exemplo

# linha: acessar da linha de índice 0 a linha de índice 2 (excluindo esta) = [0:2]
# coluna: acessar da coluna de índice 0 a coluna de 3 (excluindo esta) = [0:3] - no nosso caso, todas as colunas
print(arr[0:2 , 0:3],'\n')

# outra forma de obter o mesmo resultado é usando [:], que pega todos os elementos
print(arr[0:2 , 0:])



[[ 1  4  9]
 [16 25 36]] 

[[ 1  4  9]
 [16 25 36]]


In [36]:

# Podemos criar uma nova array com slice de outra

arr2 = arr[ : , 1:3]
arr2



array([[ 4,  9],
       [25, 36],
       [64, 81]])

In [37]:

# Podemor atribuir novos elementos a nossa array, usando slice

arr[1:2, :] = -99
arr



array([[  1,   4,   9],
       [-99, -99, -99],
       [ 49,  64,  81]])


<h2 id="Uma-imagem-vale-mais-que-mil-palavras:">Uma imagem vale mais que mil palavras:<a class="anchor-link" href="#Uma-imagem-vale-mais-que-mil-palavras:">¶</a></h2>



<p><img alt="Image of Yaktocat" src="http://www.scipy-lectures.org/_images/numpy_indexing.png"/></p>



<h4 id="SELEÇÃO-CONDICIONAL:">SELEÇÃO CONDICIONAL:<a class="anchor-link" href="#SELEÇÃO-CONDICIONAL:">¶</a></h4>



<p>Uma forma interessante de selecionar elementos baseado em alguma condição</p>


In [43]:

A = np.arange(10)
print ('A: ', A)



A:  [0 1 2 3 4 5 6 7 8 9]


In [44]:

A > 5 # retorna uma array de variáveis booleanas de acordo com a condição



array([False, False, False, False, False, False,  True,  True,  True,  True], dtype=bool)

In [45]:

# Também podemos criar uma array a partir dessa condição
B = A > 5



In [46]:

# Isso nos dá 2 opções para fazer seleção condicional, passando a condição ou passando o array como índice  

print (A [A > 5])

print (A [B])

# em ambos os casos só retorna os valores que admitem essa condição 



[6 7 8 9]
[6 7 8 9]



<h2 id="MÉTODOS">MÉTODOS<a class="anchor-link" href="#MÉTODOS">¶</a></h2>



<p>Existem inúmeros métodos que nos ajudam a trabalhar com numpy arrays, vou mostrar os mais usados:</p>


In [47]:

arr = np.arange(1,10)
print('array original: ', arr, '\n')

# Como já vimos 'reshape()' muda o formato da array, MAS o número de elementos dos dois formatos tem que coincidir, exemplo:
arr2 = arr.reshape((3,3))
print ('formato 3x3: \n' , arr2, '\n')



array original:  [1 2 3 4 5 6 7 8 9] 

formato 3x3: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [48]:

arr.max() # retorna o valor máximo



9

In [49]:

print(arr.argmax()) # retorna o índice que contém o valor máximo
arr[8] == arr[arr.argmax()]



8


True

In [50]:

arr.min() # retorna o mínimo



1

In [51]:

print(arr.argmin()) # retorna o índice que contém o valor máximo
arr[0] == arr[arr.argmin()]



0


True

In [52]:

arr.mean() # retorna a média



5.0

In [53]:

arr.std() # retorna o desvio padrão



2.5819888974716112

In [54]:

arr.sum() #retorna a soma de todos os elementos da array



45

In [55]:

### FUNÇÕES UNIVERSAIS ###

np.sqrt(arr) # retorna um array com a raiz quadrada de cada elemento



array([ 1.        ,  1.41421356,  1.73205081,  2.        ,  2.23606798,
        2.44948974,  2.64575131,  2.82842712,  3.        ])

In [56]:

np.sin(arr) # retorna um array com o seno de cada elemento



array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [57]:

np.cos(arr) # retorna um array com o cosseno de cada elemento



array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [58]:

np.exp(arr) # retorna um array com o exponencial cada elemento (e^x)



array([  2.71828183e+00,   7.38905610e+00,   2.00855369e+01,
         5.45981500e+01,   1.48413159e+02,   4.03428793e+02,
         1.09663316e+03,   2.98095799e+03,   8.10308393e+03])


<h2 id="NÚMEROS-ALEATÓRIOS:">NÚMEROS ALEATÓRIOS:<a class="anchor-link" href="#NÚMEROS-ALEATÓRIOS:">¶</a></h2>



<p>np.random</p>


In [59]:

# random ou random_sample cria floats aleatórios entre 0 e 1

print (np.random.random(2), '\n')         # passar a quantidade de números desejada
print(np.random.random_sample(4)) 



[ 0.80091316  0.24841337] 

[ 0.47808105  0.11640412  0.44931564  0.78102133]


In [60]:

# randn cria números aleatórios entre -1 e 1 (distribuição normal)
# média 0,variância 1

print (np.random.randn(2), '\n')         # passar a quantidade de números desejada
print (np.random.randn(5)) 



[-0.45987918 -0.22267994] 

[ 1.14890581 -0.75145727  2.01802619  0.49301326 -0.75460907]


In [61]:

# randint cria números inteiros aleatórios

print (np.random.randint(1,5,4), '\n')   # passar menor valor, maior valor e a quantidade de números desejada
print (np.random.randint(10,20,8)) 



[4 1 2 3] 

[17 10 11 18 15 13 16 12]



<p>Para criar números aleatórios em outro intervalo, basta usar multiplicação e soma para atingir o objetivo</p>


In [62]:

# 10 números aleatórios entre 0 e 5
5 * np.random.random(10)



array([ 3.71150636,  3.1423876 ,  3.04292747,  2.45272688,  1.74936619,
        3.86799733,  0.94209788,  4.12163146,  2.58562756,  0.4893965 ])

In [63]:

# 10 números aleatórios entre 5 e 10
5 * np.random.random(10)  + 5



array([ 7.69009536,  8.4480332 ,  9.80766937,  5.28601928,  8.11588987,
        8.70627923,  5.39802589,  8.06830133,  7.76925346,  8.85503097])