### 1. Import the NUMPY package under the name np.

In [4]:
import numpy as np

### 2. Print the NUMPY version and the configuration.

In [5]:
np.version.version

'1.13.3'

In [6]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
  NOT AVAILABLE
atlas_3_10_blas_threads_info:
  NOT AVAILABLE
atlas_3_10_blas_info:
  NOT AVAILABLE
atlas_blas_threads_info:
  NOT AVAILABLE
atlas_blas_info:
  NOT AVAILABLE
blas_info:
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    define_macros = [('NO_ATLAS_INFO', 1), ('HAVE_CBLAS', None)]
    libraries = ['blas', 'blas']
    library_dirs = ['/usr/lib/x86_64-linux-gnu']
    include_dirs = ['/usr/local/include', '/usr/include']
    language = c
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
  NOT AVAILABLE
atlas_3_10_threads_info:
  NOT AVAILABLE
atlas_3_10_info:
  NOT AVAILABLE
atlas_threads_info:
  NOT AVAILABLE
atlas_info:
  NOT AVAILABLE
lapack_info:
    libraries = ['lapack', 'lapack']
    library_dirs = ['/usr/lib/x86_64-linux-gnu

In [7]:
# note that np.version returns a file path from the file version
np.version

<module 'numpy.version' from '/usr/lib/python3/dist-packages/numpy/version.py'>

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
* Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [8]:
# note that in a DataFrame each column represent a dimension

### method 1: using numpy.random.randn¶
It returns a sample (or samples) from the “uniform distribution” over [0, 1]

* https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.rand.html


In [9]:
# an array with 1 element
np.random.rand(1)

array([ 0.22552762])

In [10]:
# an array with 2 elements 
np.random.rand(2)

array([ 0.06227832,  0.57452279])

In [11]:
# the following parameters represent the matrix's shape

In [12]:
# an array with 3 elements in 2 dimensions
np.random.rand(2, 1, 3)

array([[[ 0.09221109,  0.87901517,  0.31179825]],

       [[ 0.3157321 ,  0.10381447,  0.40560455]]])

In [13]:
# an array with 3 dimensions with 2 elements each
np.random.rand(3, 1, 2)

array([[[ 0.43589577,  0.81723953]],

       [[ 0.86117796,  0.37589803]],

       [[ 0.48098016,  0.545395  ]]])

In [14]:
# method 1: generante random numbers passing the number of dimensions
a = np.random.rand(2, 3, 5)


In [15]:
a


array([[[ 0.721342  ,  0.08609216,  0.18130627,  0.49205899,  0.65925981],
        [ 0.29651921,  0.77037018,  0.2854387 ,  0.94693338,  0.13790086],
        [ 0.05356127,  0.97316915,  0.32060881,  0.39488127,  0.02264905]],

       [[ 0.12766202,  0.36039048,  0.18347646,  0.48022023,  0.19165553],
        [ 0.06688024,  0.93380465,  0.3875774 ,  0.61307887,  0.36900289],
        [ 0.27008342,  0.99703019,  0.9774947 ,  0.60861911,  0.70746776]]])

#### Method 2: we can also use the function np.random.randn
It returns a sample (or samples) from the “standard normal” distribution.


https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randn.html

In [16]:
# an array with 4 dimensions, each dimension with  3 arrays, and each array with 2 elements
a = np.random.randn(2, # number of elements of 'outer' elements
                    3, # number of arrays inside 'inner' elements
                    5 # number of elements inside the 'inner' elements
                   )


In [17]:
a

array([[[ 0.71280391, -0.31478681,  0.21484355,  1.16150311, -0.56071946],
        [ 0.12224386,  1.1378031 , -0.06570129,  1.69481633,  0.80967327],
        [ 1.13853117,  0.91058036, -0.23796635, -0.16782549,  0.09084134]],

       [[ 0.17821325,  1.23370443, -1.0135279 , -1.01792896,  0.10987504],
        [-0.19155563,  1.13561629,  1.3703957 ,  0.61168753,  0.45775499],
        [-1.15053407,  0.66395251,  0.47990086,  1.27814023, -0.91362568]]])

### method 3
We can also create an array of integer values using np.random.randit

* check it out: https://docs.scipy.org/doc/numpy/reference/generated/numpy.random.randint.html


In [18]:
# notice that the paramaters are different from np.random.rand and np.randm.randn
a = np.random.randint(5, # longest number
                      size=[
                          # number of dimensions
                          2,
                          # number of arrays in the first array
                          3, 
                          # number of elements from the second array
                          5])

### 4. Print a.

In [19]:
print(a)

[[[1 0 0 0 2]
  [2 1 1 2 2]
  [2 0 1 0 3]]

 [[2 2 1 4 3]
  [0 2 4 0 4]
  [4 4 0 1 0]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

### 6. Print b.

In [20]:
# Method 1: using np.ones()

b = np.ones((5,2,3))

In [21]:
b

array([[[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]],

       [[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]])

In [22]:
# Method 2: using np.full()

b = np.full(
    # matrix dimention
    (5,2,3), 
    # element to fill the matrix
    1)

In [23]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


### 7. Do a and b have the same size? How do you prove that in Python code?

__Method 1__: manually compare the size of each array using the method size()

In [24]:
# comparing the size of arrays 'a' and 'b'
a.size == b.size

True

__Method 2:__ Now let's build a function to compare the sizes

In [25]:
def compare_arrays(array_1, array_2):
    if array_1.size == array_2.size:
        return('Arrays with the same size')
    else:
        return('Arrays with different sizes')

In [26]:
# After calling the function we can see that 'a' and 'b' have the same size
compare_arrays(a,b)

'Arrays with the same size'

### 8. Are you able to add a and b? Why or why not?

In [27]:
# Before perform any array operation, let's check the array's shape

In [28]:
a.shape

(2, 3, 5)

In [29]:
b.shape

(5, 2, 3)

* In order to perform operations using arrays, they have to have the same shape

In [30]:
# trying to add 'a' to 'b' using the 'plus' operator
# It won't work as they have different shapes
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [31]:
# the same error will rase if we use the add() numpy's method
np.add(a, b)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [32]:
# Method 1: transpose the data
c = np.transpose(b,
                 # define the data axis
                 (1,2,0))

In [33]:
print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]


In [34]:
# Method 2:
# using reshape function to transform the matrix structure
c = b.reshape((2, 3, 5))

In [35]:
c.shape

(2, 3, 5)

In [36]:
c

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

### 10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [37]:
# Method 1: use + as a way to concat arrays 'a' and 'c'
d_m1 = a + c

In [38]:
d_m1.shape

(2, 3, 5)

In [39]:
d_m1

array([[[2, 1, 1, 1, 3],
        [3, 2, 2, 3, 3],
        [3, 1, 2, 1, 4]],

       [[3, 3, 2, 5, 4],
        [1, 3, 5, 1, 5],
        [5, 5, 1, 2, 1]]])

In [40]:
# Method 2: use the method add() from numpy
d = np.add(a, c)

In [41]:
d.shape

(2, 3, 5)

In [42]:
d

array([[[2, 1, 1, 1, 3],
        [3, 2, 2, 3, 3],
        [3, 1, 2, 1, 4]],

       [[3, 3, 2, 5, 4],
        [1, 3, 5, 1, 5],
        [5, 5, 1, 2, 1]]])

In [43]:
# compare d_m1 to d
#they're equal
d_m1 == d

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]], dtype=bool)

### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [44]:
print(a)

[[[1 0 0 0 2]
  [2 1 1 2 2]
  [2 0 1 0 3]]

 [[2 2 1 4 3]
  [0 2 4 0 4]
  [4 4 0 1 0]]]


In [45]:
print(d)
#the values in d are equal to the a values + 1 in the corresponding positions  

[[[2 1 1 1 3]
  [3 2 2 3 3]
  [3 1 2 1 4]]

 [[3 3 2 5 4]
  [1 3 5 1 5]
  [5 5 1 2 1]]]


### 12. Multiply a and c. Assign the result to e.

In [46]:
# Method 1: using * to multiply values
e_m1 = a * c

In [47]:
e_m1.shape

(2, 3, 5)

In [48]:
e_m1

array([[[1, 0, 0, 0, 2],
        [2, 1, 1, 2, 2],
        [2, 0, 1, 0, 3]],

       [[2, 2, 1, 4, 3],
        [0, 2, 4, 0, 4],
        [4, 4, 0, 1, 0]]])

In [49]:
# Method 2: use the multiply() method from numpy
e = np.multiply(a, c)

In [50]:
e.shape

(2, 3, 5)

In [51]:
e

array([[[1, 0, 0, 0, 2],
        [2, 1, 1, 2, 2],
        [2, 0, 1, 0, 3]],

       [[2, 2, 1, 4, 3],
        [0, 2, 4, 0, 4],
        [4, 4, 0, 1, 0]]])

In [52]:
# comparing the results from method 1 and method 2 -- they're equal
e_m1 == e

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]], dtype=bool)

### 13. Does e equal to a? Why or why not?

In [53]:
# yes, array 'e' is equal to 'a' because they have equal values and shape
#since all the values in c were 1 the multiplication results are the same
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]], dtype=bool)

In [54]:
e.shape

(2, 3, 5)

In [55]:
a.shape

(2, 3, 5)

### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [56]:
# use the methods max(), min(), and mean() from numpy

In [57]:
d_max = d.max()

In [58]:
d_min = d.min()

In [59]:
d_mean = d.mean()

### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [60]:
# calling the empty function fom numpy
f = np.empty([2,3,5])

In [61]:
f

array([[[  6.91141742e-310,   1.27813439e-316,   0.00000000e+000,
           0.00000000e+000,   3.00000000e+000],
        [  4.82337433e+228,   6.14415221e-144,   1.16097020e-028,
           3.11551022e-033,   6.37075937e-062],
        [  1.58900686e-047,   3.97062373e+246,   1.16318408e-028,
           5.88173417e-062,   6.58138267e-038]],

       [[  1.52817932e+160,   1.40461115e+165,   5.04621361e+180,
           8.37170571e-144,   1.43622018e+161],
        [  3.59751658e+252,   8.93185432e+271,   4.76484771e+180,
           1.01849500e+248,   8.00801703e+159],
        [  5.63944992e-091,   9.38873537e+165,   7.93596926e-067,
           5.92939311e-062,   1.00000000e+000]]])


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.


In [63]:
for i in range(2):
    for j in range(3):
        for k in range(5):

            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]=25
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                f[i,j,k]=0
            elif d[i,j,k]==d_max:
                f[i,j,k]=100

print(f)

[[[  25.    0.    0.    0.   75.]
  [  75.   25.   25.   75.   75.]
  [  75.    0.   25.    0.   75.]]

 [[  75.   75.   25.  100.   75.]
  [   0.   75.  100.    0.  100.]
  [ 100.  100.    0.   25.    0.]]]


### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [89]:
# your code
print(d)

[[[2 1 2 2 5]
  [2 4 3 3 1]
  [3 3 5 2 4]]

 [[3 1 3 5 3]
  [5 3 2 4 1]
  [2 4 2 3 5]]]


In [90]:
print(f)

[[[ 25.   0.  25.  25. 100.]
  [ 25.  75.  75.  75.   0.]
  [ 75.  75. 100.  25.  75.]]

 [[ 75.   0.  75. 100.  75.]
  [100.  75.  25.  75.   0.]
  [ 25.  75.  25.  75. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""


In [91]:
f = f.astype(str)
for i in range(2):
    for j in range(3):
        for k in range(5):

            if d[i,j,k]>d_min and d[i,j,k]<d_mean:
                f[i,j,k]="B"
            elif d[i,j,k]>d_mean and d[i,j,k]<d_max:
                f[i,j,k]="D"
            elif d[i,j,k]==d_mean:
                f[i,j,k]="C"
            elif d[i,j,k]==d_min:
                f[i,j,k]="A"
            elif d[i,j,k]==d_max:
                f[i,j,k]="E"

print(f) 

[[['B' 'A' 'B' 'B' 'E']
  ['B' 'D' 'D' 'D' 'A']
  ['D' 'D' 'E' 'B' 'D']]

 [['D' 'A' 'D' 'E' 'D']
  ['E' 'D' 'B' 'D' 'A']
  ['B' 'D' 'B' 'D' 'E']]]
